In [43]:
import pandas as pd 

demo_df = pd.read_csv("ACSST5Y2019.S0601_data_with_overlays_2021-04-06T003209.csv") 
income_df = pd.read_csv("ACSST5Y2019.S1901_data_with_overlays_2021-04-06T003209.csv")

In [44]:
penn_tracts = ['Census Tract 87.02, Philadelphia County, Pennsylvania',
               'Census Tract 88.02, Philadelphia County, Pennsylvania',
               'Census Tract 88.01, Philadelphia County, Pennsylvania',
               'Census Tract 369, Philadelphia County, Pennsylvania']
drexel_tracts = ['Census Tract 90, Philadelphia County, Pennsylvania']
temple_tracts = ['Census Tract 153, Philadelphia County, Pennsylvania',
                 'Census Tract 147, Philadelphia County, Pennsylvania',
                 'Census Tract 146, Philadelphia County, Pennsylvania',
                 'Census Tract 377, Philadelphia County, Pennsylvania']
tju_tracts = ['Census Tract 9.02, Philadelphia County, Pennsylvania']
usciences_tracts = ['Census Tract 77, Philadelphia County, Pennsylvania']

demo_df['School'] = ''

for index, row in demo_df.iterrows():    
    tract = row['NAME']
    if tract in penn_tracts:
        row['School'] = 'University of Pennsylvania'
    elif tract in drexel_tracts:
        row['School'] = 'Drexel University'
    elif tract in temple_tracts:
        row['School'] = 'Temple University'
    elif tract in tju_tracts:
        row['School'] = 'Thomas Jefferson University'
    elif tract in usciences_tracts:
        row['School'] = 'University of the Sciences'
    else:
        continue

In [45]:
relevant_cols = ['GEO_ID', 'NAME', 'School', 'S0601_C01_001E', 'S0601_C01_004E',
                 'S0601_C01_014E', 'S0601_C01_015E', 'S0601_C01_017E', 'S0601_C01_021E', 
                 'S0601_C01_047E']
demo_df = demo_df[relevant_cols]
col_names = ['ID', 'Tract', 'School', 'Total Population', '18-24 Population', 'White Population', 
             'Black Population', 'Asian Population', 'Hispanic Population', 'Median Income']
demo_df.columns = col_names
demo_df = demo_df.drop(0, axis=0)

In [46]:
relevant_cols2 = ['GEO_ID', 'S1901_C01_013E']
income_df = income_df[relevant_cols2]

col_names2 = ['ID', 'Mean Income']
income_df.columns = col_names2
income_df = income_df.drop(0, axis=0)

In [47]:
acs_df = demo_df.merge(income_df, how='left', on='ID')
acs_df['Total Population'] = acs_df['Total Population'].astype(int)

In [48]:
acs_df

,ID,Tract,School,Total Population,18-24 Population,White Population,Black Population,Asian Population,Hispanic Population,Median Income,Mean Income
0,1400000US42101000902,"Census Tract 9.02, Philadelphia County, Pennsy...",Thomas Jefferson University,2818,17.7,71.2,6.2,15.5,4.3,40903,129430
1,1400000US42101007700,"Census Tract 77, Philadelphia County, Pennsylv...",University of the Sciences,1872,49.2,48.2,26.9,17.5,7.0,13986,57711
2,1400000US42101008702,"Census Tract 87.02, Philadelphia County, Penns...",University of Pennsylvania,2622,19.1,55.0,10.5,25.5,9.1,30649,64561
3,1400000US42101008801,"Census Tract 88.01, Philadelphia County, Penns...",University of Pennsylvania,2289,86.6,51.9,11.9,23.5,11.0,4588,64703
4,1400000US42101008802,"Census Tract 88.02, Philadelphia County, Penns...",University of Pennsylvania,6303,77.6,50.8,21.9,22.6,9.2,6920,33335
5,1400000US42101009000,"Census Tract 90, Philadelphia County, Pennsylv...",Drexel University,6201,81.3,68.6,7.8,19.6,7.6,5882,45365
6,1400000US42101014600,"Census Tract 146, Philadelphia County, Pennsyl...",Temple University,4305,50.2,35.6,47.0,11.1,5.9,9246,77043
7,1400000US42101014700,"Census Tract 147, Philadelphia County, Pennsyl...",Temple University,2686,54.1,37.8,49.7,7.4,8.7,7415,22741
8,1400000US42101015300,"Census Tract 153, Philadelphia County, Pennsyl...",Temple University,4086,61.4,50.8,33.7,10.7,5.7,9589,41733
9,1400000US42101036900,"Census Tract 369, Philadelphia County, Pennsyl...",University of Pennsylvania,5889,82.9,57.3,14.3,21.7,6.5,4478,71631
10,1400000US42101037700,"Census Tract 377, Philadelphia County, Pennsyl...",Temple University,5313,50.2,39.6,41.7,8.5,19.6,8077,30064